### ISSUE TITLE
pre-PR checklist for text-spacing

### ISSUE THREAD

**Issue by himorin** [JunTajima/i18n-tests#2]
- [x] check i18n-tests format
  - [x] meta
  - [x] test/ref
  - [x] descriptions
- [x] check title, test target
- [x] check help and/or manual for executing test

**Comment by himorin** [comment]
<del>ahh,, need to move all -000 to -001...</del>
no, could be true for wpt but not i18n-tests?

**Comment by himorin** [comment]
- why space-first need to have 'margin-left: 0.5em;' in test? (is there any case test incorrectly success with half width space removed from left side?
- 300D/FF63 etc. are the same glyph? like https://i18n-tests-w3c.himor.in/css-text/text-spacing-property/punctuation-test.html

mark meta and test/ref organization as done, d51c329

**Comment by himorin** [comment]
I think check finished for all existing ones. (not working on missing items yet.)

**Comment by himorin** [comment]
It seems we need to mark several tests with possible false positive....?

**Comment by himorin** [comment]
> It seems we need to mark several tests with possible false positive....?

added notes on false positives. let's go to PR!
